import { LuMoon, LuSun, LuSunrise } from 'react-icons/lu';

export const INTAKE_FORM_URL = 'https://forms.orendapsych.com/intake';
export const ORENDA_LOGO =
  'https://mcusercontent.com/f49e77d8389e110b514988d07/images/bd4a6ffd-dce6-72c2-e379-2223ce4d0a6b.png';

export const US_STATES = [
  { value: 'New York' },
  { value: 'Massachusetts' },
  { value: 'New Jersey' },
  { value: 'Connecticut' },
  { value: 'Alabama' },
  { value: 'Alaska' },
  { value: 'Arizona' },
  { value: 'Arkansas' },
  { value: 'California' },
  { value: 'Colorado' },
  { value: 'Delaware' },
  { value: 'Florida' },
  { value: 'Georgia' },
  { value: 'Hawaii' },
  { value: 'Idaho' },
  { value: 'Illinois' },
  { value: 'Indiana' },
  { value: 'Iowa' },
  { value: 'Kansas' },
  { value: 'Kentucky' },
  { value: 'Louisiana' },
  { value: 'Maine' },
  { value: 'Maryland' },
  { value: 'Michigan' },
  { value: 'Minnesota' },
  { value: 'Mississippi' },
  { value: 'Missouri' },
  { value: 'Montana' },
  { value: 'Nebraska' },
  { value: 'Nevada' },
  { value: 'New Hampshire' },
  { value: 'New Mexico' },
  { value: 'North Carolina' },
  { value: 'North Dakota' },
  { value: 'Ohio' },
  { value: 'Oklahoma' },
  { value: 'Oregon' },
  { value: 'Pennsylvania' },
  { value: 'Rhode Island' },
  { value: 'South Carolina' },
  { value: 'South Dakota' },
  { value: 'Tennessee' },
  { value: 'Texas' },
  { value: 'Utah' },
  { value: 'Vermont' },
  { value: 'Virginia' },
  { value: 'Washington' },
  { value: 'West Virginia' },
  { value: 'Wisconsin' },
  { value: 'Wyoming' },
];

export const timePeriods = [
  {
    label: 'Morning',
    Icon: LuSunrise,
    periods: [
      { label: '8 AM', value: '8 AM' },
      { label: '9 AM', value: '9 AM' },
      { label: '10 AM', value: '10 AM' },
      { label: '11 AM', value: '11 AM' },
    ],
  },
  {
    label: 'Afternoon',
    Icon: LuSun,
    periods: [
      { label: '12 PM', value: '12 PM' },
      { label: '1 PM', value: '1 PM' },
      { label: '2 PM', value: '2 PM' },
      { label: '3 PM', value: '3 PM' },
      { label: '4 PM', value: '4 PM' },
      { label: '5 PM', value: '5 PM' },
      { label: '6 PM', value: '6 PM' },
    ],
  },
  {
    label: 'Evening',
    Icon: LuMoon,
    periods: [
      { label: '7 PM', value: '7 PM' },
      { label: '8 PM', value: '8 PM' },
      { label: '9 PM', value: '9 PM' },
      { label: '10 PM', value: '10 PM' },
    ],
  },
];
